### ISSUE TITLE
not-so-technical | ft + nft staking together?

### ISSUE THREAD

**Issue by Fahad-pnw** [cardinal-labs/cardinal-staking#150]
Hi, thanks for making this public! you guys are doing an amazing work.

---
so, with this setup, would we be able to stake FTs while NFTs acting as a multiplier?
or more clearly, can this, at the same time stake FTs and NFTs and we could setup some conditions that reward 2x FTs to those which have a particular NFT?

**Comment by gchatz22** [comment]
Hey @Fahad-pnw. It is true you can create a pool and stake both FTs and NFTs at the same time. The protocol doesn't support the functionality you described (`reward 2x FTs to those which have a particular NFT`) however you can define different multipliers for any specific mints you want.
