### ISSUE TITLE
updateMultipliersOnRules.ts optimization

### ISSUE THREAD

**Issue by eddybounasr** [cardinal-labs/cardinal-staking#208]
the for loop on volumeLogs must be outside the loop on activeStakeEntries.
the current script is updating entry multiplier before the final volumeLogs array has been created , so a user staking 8 nfts gets updated multiple times starting with 1,3,6 instead of updating once "6"

**Comment by gchatz22** [comment]
Hey thanks for pointing this out, I assume you are talking about the `updateMultiplierOnRules` script since thats is the one that had this issue, I addressed the fix here on this PR https://github.com/cardinal-labs/cardinal-staking/pull/204
