### ISSUE TITLE
There seems to be an issue with staking missing paymentManager program / import

### ISSUE THREAD

**Issue by R-K-H** [cardinal-labs/cardinal-staking#303]
The build is having issues locating 

@cardinal/token-manager/dist/cjs/programs/paymentManager/accounts

import { PAYMENT_MANAGER_ADDRESS } from "@cardinal/token-manager/dist/cjs/programs/paymentManager";

I've check the install from yarn and indeed these files are not included or missing.

Thanks,

**Comment by gchatz22** [comment]
could try the latest cardinal staking `v1.10.7`?
