### ISSUE TITLE
Can't update reward token address, add funds, claim funds

### ISSUE THREAD

**Issue by loadev** [cardinal-labs/cardinal-staking#326]
Can't update reward token address, add funds, claim funds, i don't even see the option to choose if i want reward to be transferred, minted, or nothing.

**Comment by gchatz22** [comment]
We have been working on a v2 staking contract update that we introduced in our UI today. the new contract's reward distributor only has the `Transfer` option. What do you mean specifically you "cant update reward token address, add funds, claim funds"?

**Comment by loadev** [comment]
> 

i want to change the token that is rewarded on this pool, yesterday i could do that by selecting the dropdown box from transfer to mint, and then back to transfer and choose a new "token address", i just did that yesterday on another pool, today the option to do that is gone as you say it is "transfer" only, but if thats the case how am i supposed to change the reward token to another one?
Another thing If you changed the option to "transfer" only, why there is no option for us to add funds to the pools anymore? or to claim funds?
i even created a new pool as test, its all messed up, we add a token address, and thats it, theres no where to select add funds, or claim funds, and theres no where to select a new token address.

**Comment by loadev** [comment]
![image](https://user-images.githubusercontent.com/117549351/207483723-8b425922-1797-4062-ab6e-0ac513eb8115.png)
yesterday i could select a new Reward Mint Address here,  i just did that yesterday on another pool, today the option to do that is gone as you say it is "transfer" only, but if thats the case how am i supposed to change the reward token to another one?
Another thing If you changed the option to "transfer" only, why there is no option for us to add funds to the pools anymore? or to claim funds?
i even created a new pool as test, its all messed up, we add a token address, and thats it, theres no where to select add funds, or claim funds, and theres no where to select a new token address.

**Comment by loadev** [comment]
for reference yesterday you could:

Go on your admin panel, choose from transfer reward to mint reward, and the token you had there would be deselected, that way you could update the pool and then select again "transfer reward" and set a new "Reward Mint Address".

Today: 
you select a mint address, and it is stuck, you can't edit it anymore.


(the other thing is, no add funds option as you can clearly see on the image, and no claim funds option)

**Comment by loadev** [comment]
> alright thank you understood. Added buttons on the side of the admin page that you can use to transfer funds to the stake pool and delete a reward distributor for a pool (see sc below)
> 


Hey thanks for the quick answer,
I was able to remove the reward distributor, and claim funds.
But when i try to add a new distributor, it says transaction success but wont update it there.
The worst is that somehow the pool now has now filter for who stake 
![image](https://user-images.githubusercontent.com/117549351/207617271-2f423caf-6a28-4604-ae45-4dd39c9ac640.png)
and i can't add either collection address or creator address anymore, that means anyone can add any nft as stake on my pool.
Currently got 5000 nfts staked, and i'm getting worried that i can't fix the pool

**Comment by loadev** [comment]
**THIS ERRORS ARE SOLVED, THE CARDINAL TEAM FIXED IT QUICKLY AFTER THE UPDATE :)**

**Comment by gchatz22** [comment]
UI fix that was pushed earlier today, closing issue
